builtin-cache.o: builtin-cache.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-cache.h
builtin-dump.o: builtin-dump.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-dump.h
builtin-get-npages.o: builtin-get-npages.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-get-npages.h
builtin-get-pid.o: builtin-get-pid.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-get-pid.h
builtin-memory-localize.o: builtin-memory-localize.c parse.h \
 utils/machine.h ../standalone_kernel_module/memprof-structs.h \
 utils/rbtree.h utils/list.h utils/pqueue.h utils/symbols.h \
 utils/process.h utils/perf.h utils/data.h utils/mmap.h \
 builtin-memory-localize.h
builtin-memory-overlap.o: builtin-memory-overlap.c parse.h \
 utils/machine.h ../standalone_kernel_module/memprof-structs.h \
 utils/rbtree.h utils/list.h utils/pqueue.h utils/symbols.h \
 utils/process.h utils/perf.h utils/data.h utils/mmap.h \
 builtin-memory-overlap.h
builtin-memory-repartition.o: builtin-memory-repartition.c parse.h \
 utils/machine.h ../standalone_kernel_module/memprof-structs.h \
 utils/rbtree.h utils/list.h utils/pqueue.h utils/symbols.h \
 utils/process.h utils/perf.h utils/data.h utils/mmap.h \
 builtin-memory-repartition.h
builtin-migrate.o: builtin-migrate.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-migrate.h
builtin-object.o: builtin-object.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-object.h
builtin-pages.o: builtin-pages.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-pages.h
builtin-sched.o: builtin-sched.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-sched.h
builtin-sql.o: builtin-sql.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-sql.h
builtin-stack-repartition.o: builtin-stack-repartition.c parse.h \
 utils/machine.h ../standalone_kernel_module/memprof-structs.h \
 utils/rbtree.h utils/list.h utils/pqueue.h utils/symbols.h \
 utils/process.h utils/perf.h utils/data.h utils/mmap.h \
 builtin-stack-repartition.h
builtin-static-obj.o: builtin-static-obj.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-static-obj.h
builtin-stats.o: builtin-stats.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-stats.h
builtin-top.o: builtin-top.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-top.h
builtin-zones.o: builtin-zones.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h builtin-zones.h
parse.o: parse.c parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h utils/compatibility.h \
 builtin-memory-repartition.h builtin-stack-repartition.h builtin-dump.h \
 builtin-cache.h builtin-memory-overlap.h builtin-stats.h builtin-sched.h \
 builtin-top.h builtin-get-pid.h builtin-memory-localize.h \
 builtin-zones.h builtin-migrate.h builtin-static-obj.h \
 builtin-get-npages.h builtin-sql.h builtin-object.h builtin-pages.h
compatibility.o: utils/compatibility.c utils/../parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h utils/compatibility.h \
 utils/compatibility-machine.h
compatibility.o: utils/compatibility.h
compatibility-machine.o: utils/compatibility-machine.c utils/../parse.h \
 utils/machine.h ../standalone_kernel_module/memprof-structs.h \
 utils/rbtree.h utils/list.h utils/pqueue.h utils/symbols.h \
 utils/process.h utils/perf.h utils/data.h utils/mmap.h utils/machine.h \
 utils/compatibility-machine.h
compatibility-machine.o: utils/compatibility-machine.h \
 ../standalone_kernel_module/memprof-structs.h
data.bis.o: utils/data.bis.c utils/../parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h utils/data.h
data.bis.o: utils/data.bis.h
data.o: utils/data.c utils/../parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h utils/data.h utils/list.h \
 ../merge_data/malloc.h utils/symbols.h utils/process.h
data.o: utils/data.h
list.o: utils/list.h
machine.o: utils/machine.c utils/../parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h utils/machine.h utils/compatibility-machine.h
machine.o: utils/machine.h ../standalone_kernel_module/memprof-structs.h
mmap.o: utils/mmap.c utils/../parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h utils/mmap.h
mmap.o: utils/mmap.h
perf.o: utils/perf.c utils/../parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h utils/perf.h
perf.o: utils/perf.h
pqueue.o: utils/pqueue.c utils/pqueue.h
pqueue.o: utils/pqueue.h
process.o: utils/process.c utils/../parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h utils/process.h
process.o: utils/process.h
rbtree.o: utils/rbtree.c utils/rbtree.h
rbtree.o: utils/rbtree.h
symbols.o: utils/symbols.c utils/../parse.h utils/machine.h \
 ../standalone_kernel_module/memprof-structs.h utils/rbtree.h \
 utils/list.h utils/pqueue.h utils/symbols.h utils/process.h utils/perf.h \
 utils/data.h utils/mmap.h utils/rbtree.h utils/symbols.h \
 /usr/include/glib-2.0/glib.h /usr/include/glib-2.0/glib/galloca.h \
 /usr/include/glib-2.0/glib/gtypes.h \
 /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
 /usr/include/glib-2.0/glib/gmacros.h \
 /usr/include/glib-2.0/glib/gversionmacros.h \
 /usr/include/glib-2.0/glib/garray.h \
 /usr/include/glib-2.0/glib/gasyncqueue.h \
 /usr/include/glib-2.0/glib/gthread.h \
 /usr/include/glib-2.0/glib/gatomic.h /usr/include/glib-2.0/glib/gerror.h \
 /usr/include/glib-2.0/glib/gquark.h \
 /usr/include/glib-2.0/glib/gbacktrace.h \
 /usr/include/glib-2.0/glib/gbase64.h \
 /usr/include/glib-2.0/glib/gbitlock.h \
 /usr/include/glib-2.0/glib/gbookmarkfile.h \
 /usr/include/glib-2.0/glib/gbytes.h \
 /usr/include/glib-2.0/glib/gcharset.h \
 /usr/include/glib-2.0/glib/gchecksum.h \
 /usr/include/glib-2.0/glib/gconvert.h \
 /usr/include/glib-2.0/glib/gdataset.h /usr/include/glib-2.0/glib/gdate.h \
 /usr/include/glib-2.0/glib/gdatetime.h \
 /usr/include/glib-2.0/glib/gtimezone.h /usr/include/glib-2.0/glib/gdir.h \
 /usr/include/glib-2.0/glib/genviron.h \
 /usr/include/glib-2.0/glib/gfileutils.h \
 /usr/include/glib-2.0/glib/ggettext.h /usr/include/glib-2.0/glib/ghash.h \
 /usr/include/glib-2.0/glib/glist.h /usr/include/glib-2.0/glib/gmem.h \
 /usr/include/glib-2.0/glib/ghmac.h \
 /usr/include/glib-2.0/glib/gchecksum.h \
 /usr/include/glib-2.0/glib/ghook.h \
 /usr/include/glib-2.0/glib/ghostutils.h \
 /usr/include/glib-2.0/glib/giochannel.h \
 /usr/include/glib-2.0/glib/gmain.h /usr/include/glib-2.0/glib/gpoll.h \
 /usr/include/glib-2.0/glib/gslist.h /usr/include/glib-2.0/glib/gstring.h \
 /usr/include/glib-2.0/glib/gunicode.h \
 /usr/include/glib-2.0/glib/gutils.h \
 /usr/include/glib-2.0/glib/gkeyfile.h \
 /usr/include/glib-2.0/glib/gmappedfile.h \
 /usr/include/glib-2.0/glib/gmarkup.h \
 /usr/include/glib-2.0/glib/gmessages.h \
 /usr/include/glib-2.0/glib/gnode.h /usr/include/glib-2.0/glib/goption.h \
 /usr/include/glib-2.0/glib/gpattern.h \
 /usr/include/glib-2.0/glib/gprimes.h /usr/include/glib-2.0/glib/gqsort.h \
 /usr/include/glib-2.0/glib/gqueue.h /usr/include/glib-2.0/glib/grand.h \
 /usr/include/glib-2.0/glib/gregex.h \
 /usr/include/glib-2.0/glib/gscanner.h \
 /usr/include/glib-2.0/glib/gsequence.h \
 /usr/include/glib-2.0/glib/gshell.h /usr/include/glib-2.0/glib/gslice.h \
 /usr/include/glib-2.0/glib/gspawn.h \
 /usr/include/glib-2.0/glib/gstrfuncs.h \
 /usr/include/glib-2.0/glib/gstringchunk.h \
 /usr/include/glib-2.0/glib/gtestutils.h \
 /usr/include/glib-2.0/glib/gthreadpool.h \
 /usr/include/glib-2.0/glib/gtimer.h \
 /usr/include/glib-2.0/glib/gtrashstack.h \
 /usr/include/glib-2.0/glib/gtree.h \
 /usr/include/glib-2.0/glib/gurifuncs.h \
 /usr/include/glib-2.0/glib/gvarianttype.h \
 /usr/include/glib-2.0/glib/gvariant.h \
 /usr/include/glib-2.0/glib/gversion.h \
 /usr/include/glib-2.0/glib/deprecated/gallocator.h \
 /usr/include/glib-2.0/glib/deprecated/gcache.h \
 /usr/include/glib-2.0/glib/deprecated/gcompletion.h \
 /usr/include/glib-2.0/glib/deprecated/gmain.h \
 /usr/include/glib-2.0/glib/deprecated/grel.h \
 /usr/include/glib-2.0/glib/deprecated/gthread.h
symbols.o: utils/symbols.h
